name: Recover Files

on:
 push:
  branches: [main]

jobs:
 recover:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Commit arquivos do codespaces
      run: |
        git add .
        git commit -m "Recuperando codespaces" || echo "Nada para comitar"
        git push
